### ISSUE TITLE
Better error reporting for bibtex pipeline

### ISSUE THREAD

**Issue by wouterbulten** [DIAGNijmegen/website-content#69] opened 2019-07-15 09:43 UTC
Currently the bibtex pipeline only show general errors, e.g.:

```
Traceback (most recent call last):
  File "plugins/bib_writer.py", line 346, in <module>
    pubgen.generate_md_bibitem()
  File "plugins/bib_writer.py", line 145, in generate_md_bibitem
    index, global_index, string_rules = bibtexlib.read_bibtex_file(bib_file)
  File "/home/travis/build/DIAGNijmegen/website-content/website-pathology/plugins/bibtex/bibtexlib.py", line 300, in read_bibtex_file
    key, entry_dict = get_entry(entry)
  File "/home/travis/build/DIAGNijmegen/website-content/website-pathology/plugins/bibtex/bibtexlib.py", line 199, in get_entry
    key_index = entry.index(',')
ValueError: substring not found
```

It would be nice if the pipeline shows which bibentry was related to this error. That would speed up debugging.

**Comment by wouterbulten** [comment] 2019-07-17 07:56
Errors introduced with the new neuro-website:

```
Failed parsing bibentry for rashindra manniesing and bib key oei14a. This entry is skipped.
Traceback (most recent call last):
  File "plugins/bib_writer.py", line 75, in __get_publications_by_author
    if last.lower() in lastnames and first[0].lower() == firstname[0].lower():
IndexError: string index out of range

Failed writing bib entry pate16 to markdown file.
Traceback (most recent call last):
  File "plugins/bib_writer.py", line 256, in __write_single_publication_md
    _, pub_details = html_format.apply(global_index[bibkey])
TypeError: 'NoneType' object is not iterable

List of bibkeys returning UnicodeEncodeError
oei17

Time to process diag.bib  1.2169092084220907
Time to create 4690 MD files  5.864710214092021
Failed writing html for publication list for mann99a, skipping this entry.
Traceback (most recent call last):
  File "plugins/bib_writer.py", line 185, in __write_list_publications_md
    html_bibkey, year, pub_type, pub_details = self.__append_publication_md(global_index, bib_key, html_format)
  File "plugins/bib_writer.py", line 297, in __append_publication_md
    html_to_write, pub_details = html_format.apply(bib_item)
TypeError: 'NoneType' object is not iterable

Failed writing html for publication list for mann09a, skipping this entry.
Traceback (most recent call last):
  File "plugins/bib_writer.py", line 185, in __write_list_publications_md
    html_bibkey, year, pub_type, pub_details = self.__append_publication_md(global_index, bib_key, html_format)
  File "plugins/bib_writer.py", line 297, in __append_publication_md
    html_to_write, pub_details = html_format.apply(bib_item)
TypeError: 'NoneType' object is not iterable

Failed writing html for publication list for mann09b, skipping this entry.
Traceback (most recent call last):
  File "plugins/bib_writer.py", line 185, in __write_list_publications_md
    html_bibkey, year, pub_type, pub_details = self.__append_publication_md(global_index, bib_key, html_format)
  File "plugins/bib_writer.py", line 297, in __append_publication_md
    html_to_write, pub_details = html_format.apply(bib_item)
TypeError: 'NoneType' object is not iterable

Failed writing html for publication list for mann09, skipping this entry.
Traceback (most recent call last):
  File "plugins/bib_writer.py", line 185, in __write_list_publications_md
    html_bibkey, year, pub_type, pub_details = self.__append_publication_md(global_index, bib_key, html_format)
  File "plugins/bib_writer.py", line 297, in __append_publication_md
    html_to_write, pub_details = html_format.apply(bib_item)
TypeError: 'NoneType' object is not iterable

Failed writing html for publication list for pate16, skipping this entry.
Traceback (most recent call last):
  File "plugins/bib_writer.py", line 185, in __write_list_publications_md
    html_bibkey, year, pub_type, pub_details = self.__append_publication_md(global_index, bib_key, html_format)
  File "plugins/bib_writer.py", line 297, in __append_publication_md
    html_to_write, pub_details = html_format.apply(bib_item)
TypeError: 'NoneType' object is not iterable
```

**Comment by wouterbulten** [comment] 2019-07-17 07:58
@ghumpire I've added some rudimentary error reporting to the bibparser (at every point that the built broke, see comment above). Could you maybe take a look at this and see whether the changes make sense?

I'm not sure why it broke on these bibentries. Do you have any idea?

**Comment by ghumpire** [comment] 2019-07-17 13:03
Thanks for integrating the error reporting. I just moved a piece of code that should go in the try statement.  The bibentries with errors were fixed via b38d0aa. Those bibtentries were Misc and Electronic types, which we did not have in previous publications. Now, I added a default publication type, they will appear as "Other publications".

**Comment by ghumpire** [comment] 2019-07-17 13:21
I had to updated the diag.bib, the entry Oei14a had authors "Marcel T. H. Oei and Manniesing and ..." (it has only Rashindra's last name, I just added it to fix the issue "Marcel T. H. Oei and **Rashindra** Manniesing and ...".

**Comment by MeykeHermsen** [comment] 2019-07-17 15:23
I have asked Bart about the error reporting, but I see that this is fixed already. I could not reproduce the error that was mentioned at the top. Sorting of diag.bib might not have been the issue then..

**Comment by wouterbulten** [comment] 2019-08-05 14:12
@ghumpire can we close this issue?

**Comment by ghumpire** [comment] 2019-08-05 14:16
Yes, we can close it.

**Closed by ghumpire** 2019-08-05 14:16 UTC
Labels: enhancement
